library(MASS)
library(ISLR)
library(car)
#fix(Boston)
names(Boston)
scatterplotMatrix(x=Boston)
# multiple linear regression
slr <- lm(medv ~ lstat, data = Boston)
mlr <- lm(medv ~ lstat + age, data = Boston)
summary(mlr)
summary(slr)
anova(mlr)
mlr0 <- lm(medv ~ ., data=Boston)
summary(mlr0)
mlr1 <- lm(medv ~ .-age, data=Boston)
summary(mlr1)
mlr2 <- lm(medv ~ .-age-indus, data=Boston)
summary(mlr2)
anova(mlr2)
vif(mlr)
vif(mlr0)
vif(mlr1)
# include interaction terms
mlr3 <- lm(medv ~ lstat*black, data=Boston)
mlr4 <- lm(medv ~ lstat + black, data=Boston)
summary(mlr4)
# non-linear transformations of the predictors
mlr5 <- lm(medv ~ lstat, data = Boston)
mlr6 <- lm(medv ~ lstat + I(lstat^2), data = Boston)
mlr7 <- lm(medv ~ lstat + log(lstat), data = Boston)
summary(mlr7)
anova(mlr5, mlr7)
par(mfrow=c(2,2))
plot(mlr7)
# qualitative predictors
attach(Carseats)
names(Carseats)
scatterplotMatrix(Carseats)
contrasts(ShelveLoc)
car.mlr1 <- lm(Sales ~ ., data = Carseats)
summary(car.mlr1)
plot(car.mlr1)
